### ISSUE TITLE
Is it possible creating constraint for OMK in excel?

### ISSUE THREAD

**Issue by adissadis** [posm/OpenMapKitAndroid#167]
Hi All,

I want to create template form for OMK using excel and wondering if is it possible to create constraint in excel? If yes, are there any documentation or sample file (in excel) for using constraint?

My idea is i want to create one form for OMK that using constraint feature for example, hide some question if the data not showing place of worship, create multiple select question, required, etc (like all the constraint type that listed in [here](http://openmapkit.org/docs_constraints.html).

Those link only show us to create constraint in json and I wondering if we can create constraint in excel just like the way we create constraint in excel when we create question for ODK. Like this example:
![image](https://user-images.githubusercontent.com/2520159/38609902-880cc3c2-3da9-11e8-858a-841897dcb19c.png)

Any help I really appreciate it! Thank you!

**Comment by danbjoseph** [comment]
for core questions on the `survey` worksheet all the normal XLSForm constraint syntax rules apply. although the keys/values used in OMK are defined on an `osm` worksheet in your XLSForm file, constraints for OMK can only be added via an accompanying json file. sorry, it's not ideal. we're always looking for ways to improve the software and are open to suggestions!

**Comment by adissadis** [comment]
I see, thank you for your explanation. Hopefully OMK will have same capabilities like all the normal XLSForm constraint syntax rules. I will close this issue now. Thank you!
